//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momiji.Bot.V5.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Momiji.Bot.V5.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;console/ConsoleStyle.css&quot; /&gt;
        ///    &lt;script src=&quot;console/ConsoleScript.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;background-color: black; color: white;&quot; onload=&quot;init()&quot;&gt;
        ///    &lt;div class=&quot;logo&quot;&gt;
        ///        888b&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbspd888&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbsp&amp;nbs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleHeader {
            get {
                return ResourceManager.GetString("ConsoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var httpRequestStatus;
        ///var timestep = 5000;
        ///
        ///function init() {
        ///    &quot;use strict&quot;;
        ///    startLoop();
        ///}
        ///
        ///function getRequest() {
        ///    &quot;use strict&quot;;
        ///    try {
        ///        return new ActiveXObject(&quot;Msxml2.XMLHTTP&quot;);
        ///    } catch (e) {
        ///        try {
        ///            return new ActiveXObject(&quot;Microsoft.XMLHTTP&quot;);
        ///        } catch (err) { }
        ///    }
        ///    if (typeof XMLHttpRequest !== &quot;undefined&quot;) {
        ///        return new XMLHttpRequest();
        ///    }
        ///    return null;
        ///}
        ///
        ///function startLoop() {
        ///    &quot;use strict&quot;;
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleScript {
            get {
                return ResourceManager.GetString("ConsoleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table {
        ///    width: 640px;
        ///    max-width: 640px;
        ///    min-width: 640px;
        ///    color: white;
        ///    font: 12pt Unifont, Arial;
        ///    table-layout: fixed;
        ///}
        ///
        ///div.logo {
        ///    font: 12pt Unifont;
        ///    color: yellow;
        ///}
        ///
        ///.bold {
        ///    font-weight: bold;
        ///}
        ///
        ///.row1 {
        ///    white-space: nowrap;
        ///    vertical-align: text-top;
        ///    min-width: 70px;
        ///    max-width: 70px;
        ///}
        ///
        ///.row2 {
        ///    vertical-align: text-top;
        ///    min-width: 120px;
        ///    max-width: 120px;
        ///    word-wrap: break-word;
        ///}
        ///
        ///.row3 {
        ///    vertical- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleStyle {
            get {
                return ResourceManager.GetString("ConsoleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MomijiIcon {
            get {
                object obj = ResourceManager.GetObject("MomijiIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
